export const pillars=['Clean mobility','Water access','Energy & storage','Agri value chains','Financial inclusion','Skills & jobs'];
export const programs=[{name:'CORE Energy',services:['Energy infrastructure','Energy appliances']},{name:'CORE Water',services:['Water supply','Water management']},{name:'CORE Transport',services:['Charging and swapping stations','EVs and E-bikes','Transportation services (P-2)']},{name:'CORE Health',services:['Pharmacy','Health insurance','Pharmaceutical (P-2)','Specialized health services (P-2)']},{name:'CORE Agriculture',services:['Agricultural inputs','Irrigation technologies','Farming','Agricultural logistics (P-2)','Agro processing (P-2)','Market access (P-2)']},{name:'CORE Microfinance',services:['Microcredit services','Financial education','Digital banking solutions (P-2)']}];
export const projects=[
{name:'Charging Stations',category:'Clean transportation',location:'Ethiopia',status:'Active',image:'Rec',alt:'Infrastructure visualization from CORE Development',description:'Deploying charging stations for electric vehicles in major cities across Ethiopia.',features:['Reduces GHG emissions','Charging and swapping stations','Job creation and training','Electric vehicle infrastructure'],capacity:'Electric vehicle ecosystem',communities:'Major cities',beneficiaries:'1M+ commuters',maps:'https://www.google.com/maps/dir/?api=1&destination=9.0230011%2C38.7752537'},
{name:'Rural Economic Centers',category:'Community development',location:'Ethiopia',status:'',image:'Rec',alt:'CORE rural economic center architectural visualization',description:'Empowering Kebele and Woreda Administration Centers through integrated economic solutions.',features:['Job creation programs','Transportation services','Healthcare access','Agricultural support services','Banking and financial services'],capacity:'25.2 kW PV · 96.5 kWh ESS · 20 kW backup',communities:'15+ centers',beneficiaries:'50,000+ people'},
{name:'SmartTap Water Initiative',category:'Water access',location:'Rural Ethiopia',status:'Scaling',image:'SmartTap',alt:'Original SmartTap water initiative photograph',description:'Solar-powered, prepaid water systems managed by women-led SMEs, designed to make rural water access more reliable.',features:['Women-led SME management','Solar-powered systems','Prepaid water access','Scalable and replicable model','Increased water reliability'],capacity:'Solar-powered water systems',communities:'25+ villages',beneficiaries:'100,000+ people'},
{name:'EV Revolution Initiative',category:'Clean transportation',location:'Urban Ethiopia',status:'Pilot phase',image:'TukTuk',alt:'Electric three-wheeler from the EV Revolution Initiative',description:'Clean transportation powered by renewable energy, designed to reduce emissions, create jobs and lower fuel imports.',features:['100% renewable energy','Reduces GHG emissions','Charging and swapping stations','Job creation and training','Electric vehicle infrastructure'],capacity:'Electric vehicle ecosystem',communities:'3 major cities',beneficiaries:'1M+ commuters'}];
export const founders=[
{name:'Dr. Eng. Seleshi Bekele',role:'Co-Founder & Chief Water Resources Advisor',image:'seleshi',linkedin:'https://www.linkedin.com/in/seleshi-bekele-awulachew-b546b668/',expertise:['International development','Water resources','Sustainable development','Policy development'],bio:'Seleshi Bekele (ስለሺ በቀለ) is an Ethiopian politician and academic. His experience includes Chief Negotiator and Advisor on Transboundary Rivers and GERD at the Office of the Prime Minister of Ethiopia from 2021, Minister of Water, Irrigation and Energy (2018-2021), and Ethiopia’s ambassador to the United States (2022-2024).',education:['PhD in Hydraulic Engineering, TU Dresden','MSc in Civil Engineering, Newcastle Upon Tyne','BSc in Civil Engineering, Addis Ababa University'],experience:['Former Dean, Arba Minch Water Technology Institute','Head of International Water Management Institute for the Nile Basin in East Africa','UNECA; Interregional Advisor on Water, Energy and Capacity Development at United Nations DESA','Chief Negotiator and Advisor for the Prime Minister at ministerial level','Former Minister of Water, Irrigation and Energy (2018-2021)','Ambassador to the United States (2022-2024)']},
{name:'Dr. Amir Aman',role:'Co-Founder & Chief Health Strategy Officer',image:'Amir',linkedin:'https://www.linkedin.com/in/amir-aman-448323153/',expertise:['Public health','Strategic planning','Leadership','Global health financing'],bio:'An Ethiopian physician and public-health leader who served as Minister of Health. His work spans global health financing, philanthropy, policy design, implementation and resource mobilization, including roles at the Susan Thompson Buffett Foundation and the World Bank’s Global Financing Facility.',education:['Doctor of Medicine, Addis Ababa University','MSc in Public Health, University of the Western Cape'],experience:['Former Minister of Health, Ethiopia','Former Senior Advisor, Susan Thompson Buffett Foundation','Former Country Operations Lead, Global Financing Facility / World Bank','Leadership, policy, implementation and resource mobilization']},
{name:'Eng. Hizkyas Dufera',role:'Co-Founder & Chief Technology Officer',image:'Hizikias',linkedin:'https://www.linkedin.com/in/hizkyas-dufera-a8055b173/',expertise:['Project finance','Renewable energy','Strategic leadership','Innovation'],bio:'An Ethiopian engineer and entrepreneur working on solar and renewable energy solutions in Ethiopia and globally. His electrical engineering background supports energy policy, irrigation and sustainable development.',education:['BSc in Electrical, Electronics and Communications Engineering, University of Maryland','MS in Electric and Electronics Engineering, Rensselaer Polytechnic Institute'],experience:['Former U.S. aerospace and energy sector leader with renewable energy grant financing experience','Founder of Dufsar Energy LLC, delivering solar and renewable energy solutions globally','Spearheaded CRISP for climate-resilient agriculture','Energy and irrigation policy reforms at Ethiopia’s Ministry of Water, Irrigation and Energy','Senior advisor, entrepreneur and policy innovator']}];
export const chargeFeatures=['Real-time station availability and live charger status','Estimated State of Charge for AC and DC sessions','Battery health monitoring with scientific degradation analysis','iOS Live Activity and Dynamic Island session tracking','Smart queue management with real-time position updates','Up to 3 vehicle profiles per account','Guest vehicle mode for operators charging customer cars','Instant digital receipts with session details','Loyalty rewards on every session','Power outage detection with proximity alerts','Idle fee protection with automatic safeguards','Offline-ready intelligent data caching','End-to-end encrypted transactions'];
export const appStore='https://apps.apple.com/tr/app/core-charge/id6762530025';
export const playStore='https://play.google.com/store/apps/details?id=org.coredevelopment.app';
