import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Outlet,createRootRouteWithContext,HeadContent,Scripts,useRouter} from '@tanstack/react-router';
import {useEffect,type ReactNode} from 'react';
import appCss from '../styles.css?url';
import {reportHiggsfieldError} from '../lib/higgsfield-error-reporting';
import meta from '../app-meta.json';
import {scrollScrubTheme} from '../scroll-scrub-scenes';
declare const __HF_DESIGN_INSPECTOR__:boolean;
const site='https://core-development.higgsfield.app';
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:meta.og_title},{name:'description',content:meta.og_description},{name:'author',content:'CORE Development'},{name:'theme-color',content:scrollScrubTheme.background},{name:'robots',content:'index, follow, max-image-preview:large'},{property:'og:title',content:meta.og_title},{property:'og:description',content:meta.og_description},{property:'og:type',content:'website'},{property:'og:site_name',content:'CORE Development'},{property:'og:image',content:site+'/assets/core-og.png'},{property:'og:image:width',content:'1200'},{property:'og:image:height',content:'630'},{name:'twitter:card',content:'summary_large_image'},{name:'twitter:title',content:meta.og_title},{name:'twitter:description',content:meta.og_description},{name:'twitter:image',content:site+'/assets/core-og.png'}],links:[{rel:'stylesheet',href:appCss},{rel:'icon',href:'/favicon.ico'},{rel:'icon',type:'image/png',sizes:'32x32',href:'/favicon-32.png'},{rel:'apple-touch-icon',href:'/apple-touch-icon.png'},{rel:'manifest',href:'/site.webmanifest'},{rel:'preconnect',href:'https://fonts.googleapis.com'},{rel:'preconnect',href:'https://fonts.gstatic.com',crossOrigin:'anonymous'},{rel:'stylesheet',href:'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Outfit:wght@400;500;600;700&display=swap'}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:()=> <main className="error-view"><h1>Page not found.</h1><a href="/">Return to CORE Development</a></main>,errorComponent:ErrorView});
function ErrorView({reset}:{reset:()=>void}){const router=useRouter();return <main className="error-view"><h1>This page could not load.</h1><button onClick={()=>{router.invalidate();reset()}}>Try again</button><a href="/">Return home</a></main>}
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'CORE Development',url:site,logo:site+'/assets/original/CoreLogo.png',description:meta.og_description,email:'info@coredevelopment.org',telephone:'+251911781859',address:{'@type':'PostalAddress',addressLocality:'Addis Ababa',addressCountry:'ET'},sameAs:['https://www.coredevelopment.org']})}}/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();useEffect(()=>{if(!__HF_DESIGN_INSPECTOR__)return;void import('../module/design-inspector/runtime').then(({installHiggsfieldDesignInspector})=>installHiggsfieldDesignInspector()).catch(error=>reportHiggsfieldError(error instanceof Error?error:new Error('Inspector unavailable'),{boundary:'design_inspector_import'}))},[]);return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
